apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.28.0 # Match with Vault’s latest compatible chart
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: vault-values
      valuesKey: values.yaml


  values:
    injector:
      enabled: false
    server:
      dev:
        enabled: true  # ✅ Use for now, switch to full Raft later
      dataStorage:
        enabled: false
