apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
        policy-type: "app"
    spec:
      containers:
        - name: health-api
          image: ghcr.io/T-Py-T/health-api:v0.2.6
          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: health-api-configmap
            - secretRef:
                name: health-api-container-env

      restartPolicy: Always
