apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: health-api-container-env
  namespace: health
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: health-db-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: health-db-password
