apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shelly-container-env
  namespace: shelly
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: shelly-mqtt-username
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: shelly-mqtt-password
    - secretKey: PG_USER
      remoteRef:
        key: shelly-db-username
    - secretKey: PG_PASSWORD
      remoteRef:
        key: shelly-db-password
