apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: linkding
  namespace: linkding
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkding
  service:
    port: 80
    gateways:
      - istio-system/istio-ingressgateway
    hosts:
      - linkding.{{ PLACEHOLDER_DOMAIN }}
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        interval: 30s
        thresholdRange:
          min: 99
