apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - configmap.yaml
  - cloudflare.yaml
  - canary.yaml
  - istio.yaml

  # - database-cnpg.yaml
  # - scheduled-backup-cnpg.yaml
  # - networkpolicy.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-production
