apiVersion: apps/v1
kind: Deployment
metadata:
  name: zettelkasten-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zettelkasten-tracker
  template:
    metadata:
      labels:
        app: zettelkasten-tracker
        try: "1"
        policy-type: "app"
    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 3000
      #   fsGroup: 2000
      containers:
        - name: zettelkasten-tracker
          image: ghcr.io/T-Py-T/zettelkasten-tracker:v0.3.4 # {"$imagepolicy": "flux-system:zettelkasten-tracker"}
          # securityContext:
          #   allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: zettelkasten-tracker-configmap
            - secretRef:
                name: zettelkasten-tracker-container-env
          ports:
            - containerPort: 3009
              protocol: TCP

      restartPolicy: Always
