apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zettelkasten-tracker-container-env
  namespace: zettelkasten-tracker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: zettelkasten-tracker-db-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: zettelkasten-tracker-db-password
