apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: 8.13.4 # match to current compatibility
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
    minimumMasterNodes: 1
    esJavaOpts: "-Xmx1g -Xms1g"
    resources:
      requests:
        cpu: "100m"
        memory: "2Gi"
