apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: 8.13.4
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    elasticsearchHosts: "http://elasticsearch-master.elastic-system.svc.cluster.local:9200"
